FROM python:3.9-slim

# Install dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy source code
COPY . .

# Expose the necessary port
EXPOSE 5000

# Run the app
CMD ["python", "forecasting-service.py"]
